/*
 * Copyright 2026 Black Mountain AI (BMAI)
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

/**
 * Emits the machine-checkable half of the parity audit as markdown.
 *
 * `npm run report > ../parity/reports/YYYYMM-roundN-parity.md`
 *
 * This is not the audit. The audit is a person who built neither build reading
 * both, satisfying themselves that the declared divergences are the only ones,
 * and signing. This report tells that person what the machine already checked,
 * so their attention goes where a machine cannot look: whether the informational
 * content of the two builds is the same *in meaning*, and whether a declared
 * divergence is honestly declared.
 */

import { DECLARED_DIVERGENCES } from './divergences.ts';

const rows = (kind: string) => DECLARED_DIVERGENCES.filter((d) => d.kind === kind);

const lines: string[] = [
  '# Parity audit report — machine-checked portion',
  '',
  '> Generated by `@guiderails/parity-audit`. **This is not the audit.** An auditor who built neither build must read both, satisfy themselves that the divergences declared below are the only ones, and sign §4. The machine checks what it can; the auditor checks what it cannot.',
  '',
  '## 1. What the machine checked',
  '',
  'Run `npm test` in `03-reference-implementation/parity/`. The suite fails the build if any of these stop holding:',
  '',
  '| Check | Claim |',
  '|---|---|',
  '| Shared rules module | Both builds resolve one SSPD-2026 module; rate, thresholds, s11 boundary, due-days, instrument id and rules version are the values FIXTURE-SPEC fixes. |',
  '| Field-set parity | Every journey step exposes the same fields, fully specified, on both builds. |',
  '| Outcome parity | The same applicant, completed through the human path on both builds, yields exactly one effect, with identical recorded values. |',
  '| Validation parity | Valid input is accepted and invalid input rejected identically, normalising for B-08 (the baseline signals rejection by re-rendering, not by status code). |',
  '| Duplicate protection | A repeated identical submission returns the original reference and creates no second effect, on both builds. |',
  '| Surface inventory | Conformant-only and baseline-only surfaces are exactly those declared; nothing else appears on one and not the other. |',
  '| Divergence classification | Every declared divergence is classified, and each derived one names the catalogued pattern that forces it. |',
  '',
  '## 2. Declared divergences',
  '',
  'The parity boundary: anything not below is a parity defect.',
  '',
  '### 2.1 Catalogued baseline patterns',
  '',
  'Derivations in `PATTERN-CATALOGUE.md`. The baseline exhibits these; the conformant build does not.',
  '',
  '| ID | Divergence |',
  '|---|---|',
  ...rows('catalogued').map((d) => `| ${d.id} | ${d.description} |`),
  '',
  '### 2.2 Conformance features',
  '',
  'The conformant build implements these; the baseline does not.',
  '',
  '| ID | Divergence |',
  '|---|---|',
  ...rows('conformance').map((d) => `| ${d.id} | ${d.description} |`),
  '',
  '### 2.3 Derived divergences — *read these closely*',
  '',
  'Forced by a catalogued pattern rather than chosen. These are the ones an audit misses: they look exactly like defects, because nothing in the conformance feature set or the anti-pattern catalogue names them directly. Each must state the pattern that causes it.',
  '',
  ...rows('derived').flatMap((d) => [
    `**${d.id}** — caused by **${d.causedBy}**`,
    '',
    d.description,
    '',
  ]),
  '## 3. What the machine cannot check',
  '',
  'The auditor must form a view on each, and record it:',
  '',
  '1. **Informational content, identical in meaning.** Both builds must tell the person the same things. Automated comparison can only see that fields and outcomes match; whether the baseline\'s prose says the same thing as the conformant build\'s prose is a reading task.',
  '2. **Whether a declared divergence is honestly declared.** A divergence can be real, documented, and still be a way of making the baseline worse than the pattern warrants. Check each against its derivation.',
  '3. **Whether any derived divergence is undeclared.** Ask of every catalogued pattern: what else in the system was keyed on the concept this pattern removes?',
  '4. **Whether the baseline is worse than the wild.** The control must replicate documented practice, not exceed it.',
  '',
  '## 4. Auditor sign-off',
  '',
  '| Field | Value |',
  '|---|---|',
  '| Auditor |  |',
  '| Built neither the fixture nor the harness (required) | ☐ |',
  '| Fixture commit |  |',
  '| Date |  |',
  '| Machine checks passing at that commit | ☐ |',
  '| §3 items reviewed and recorded | ☐ |',
  '| Undeclared divergences found | none / *list* |',
  '| Signature |  |',
  '',
  '> A parity audit filed without §3 reviewed is a test run, not an audit.',
  '',
];

console.log(lines.join('\n'));
