/*
 * Copyright 2026 Black Mountain AI (BMAI)
 * Licensed under the Apache License, Version 2.0.
 *
 * Generates techniques.json: for every success criterion, either the techniques
 * that satisfy it or an explicit gap.
 *
 * "Techniques mapped or gap noted" is in CLAUDE.md's definition of done for a
 * criterion change, and nothing checked it. This makes the claim machine-
 * readable and the gaps countable.
 *
 * The strongest technique evidence this repository has is not prose: it is the
 * conformant build. Where the reference implementation cites a criterion in the
 * code or the test that enforces it, that citation IS the technique —
 * demonstrated, run in CI, and impossible to assert without also shipping it.
 * Those mappings are derived, not written. Everything else is an honest gap.
 *
 *     node 02-model/techniques/build.mjs
 */

import { readFileSync, writeFileSync, readdirSync } from 'node:fs';
import { fileURLToPath } from 'node:url';

const root = fileURLToPath(new URL('../../', import.meta.url));
const model = readFileSync(root + '02-model/MODEL.md', 'utf8');

const criteria = [...model.matchAll(/^- \*\*(\d+\.\d+\.\d+) \((A|AA|AAA)\)\*\* (.+)$/gm)].map((m) => ({
  id: m[1],
  level: m[2],
  text: m[3].replace(/\*\*/g, ''),
}));

/** Principle-level technique prose, as MODEL.md already records it. */
const principleTechniques = {};
for (const m of model.matchAll(/^\*Techniques:\* (.+?)(?: \*Rationale:\*|$)/gms)) {
  const before = model.slice(0, m.index);
  const principle = [...before.matchAll(/^### Principle (\d)/gm)].pop()?.[1];
  if (principle) principleTechniques[principle] = m[1].split('*Rationale:*')[0].trim();
}

/** Files under 03-* that cite a criterion, with the line that does it. */
function* sourceFiles(dir) {
  for (const entry of readdirSync(dir, { withFileTypes: true })) {
    if (entry.name === 'node_modules') continue;
    const path = `${dir}/${entry.name}`;
    if (entry.isDirectory()) yield* sourceFiles(path);
    else if (/\.ts$/.test(entry.name)) yield path; // tests included: a criterion a test enforces is a criterion demonstrated
  }
}

const demonstrations = new Map(); // criterion -> [{file, line}]
for (const file of sourceFiles(root + '03-reference-implementation')) {
  const rel = file.slice(root.length);
  readFileSync(file, 'utf8').split('\n').forEach((text, i) => {
    for (const m of text.matchAll(/\b([1-5]\.\d\.\d)\b/g)) {
      if (!criteria.some((c) => c.id === m[1])) continue;
      if (!demonstrations.has(m[1])) demonstrations.set(m[1], []);
      const list = demonstrations.get(m[1]);
      if (list.length < 3 && !list.some((d) => d.file === rel)) list.push({ file: rel, line: i + 1 });
    }
  });
}

const records = criteria.map((c) => {
  const shown = demonstrations.get(c.id) ?? [];
  return {
    criterion: c.id,
    level: c.level,
    demonstratedBy: shown,
    principleTechniques: principleTechniques[c.id[0]] ?? null,
    gap:
      shown.length > 0
        ? null
        : principleTechniques[c.id[0]]
          ? 'No technique demonstrated in the reference implementation. The principle names candidate techniques; none is mapped to this criterion, and none is exercised by a test.'
          : 'No technique demonstrated, and this criterion\'s principle publishes no technique prose at all.',
  };
});

const mapped = records.filter((r) => !r.gap).length;
writeFileSync(
  root + '02-model/techniques/techniques.json',
  JSON.stringify(
    {
      $comment:
        'GENERATED by build.mjs. For every criterion: the techniques demonstrated by the reference implementation, or an explicit gap. Do not hand-edit.',
      modelVersion: /^\*\*Version ([\d.]+) —/m.exec(model)[1],
      criteria: records.length,
      demonstrated: mapped,
      gaps: records.length - mapped,
      records,
    },
    null,
    1,
  ) + '\n',
);
console.error(`techniques.json: ${records.length} criteria, ${mapped} demonstrated, ${records.length - mapped} gaps`);
